### PR TITLE
replace '/' literals with path.sep

### PR DESCRIPTION
**Pull request by gforceg**
(enforces first philosophical bullet point in README.md 'work on every platform')

Please consider merging this and publishing to npmjs. It is an awesome project and it doesn't look like it is actively being maintained.

Thanks!

### CODE REVIEW

**Comment by mickhrmweb** [comment]
Hi @gforceg, thanks for your contribution! And you're right, the project isn't really maintained, I stopped writing Node / JS in general years ago unfortunately.

If you have an interest in the project, would you consider taking ownership of it?

**Comment by beefsack** [comment]
Hi @gforceg, thanks for your contribution! And you're right, the project isn't really maintained, I stopped writing Node / JS in general years ago unfortunately.

If you have an interest in the project, would you consider taking ownership of it?

**Comment by gforceg** [comment]
Hi @beefsack, thanks. And thanks for making making such a great tool. Yes, I will gladly continue working on it.

**Comment by gforceg** [comment]
I submitted a request to npm to see how the package can be moved from one npmjs account to another.
If this is an option then projects can leave their npm dependencies unchanged.

**Comment by beefsack** [comment]
@gforceg cheers for chasing that up, that was actually the one thing I was a bit concerned about. Have you had any response from NPM yet?

**Comment by gforceg** [comment]
I sent them an email and then needed me to CC you but I just haven't had time.
I sure do! I'm[ gforceg on npmjs](http://npmjs.com/~gforceg) as well. I'm find with doing it that way.

Thanks again.

**Comment by mickhrmweb** [comment]
@gforceg have added you as an owner of the NPM package, cheers! 👍 

Tried to transfer ownership of the repo to you, but you already have a fork so it didn't allow me. Might not be a big issue anyway, I can add a node to the README to say yours is now the source of truth.

**Comment by beefsack** [comment]
@gforceg have added you as an owner of the NPM package, cheers! 👍 

Tried to transfer ownership of the repo to you, but you already have a fork so it didn't allow me. Might not be a big issue anyway, I can add a node to the README to say yours is now the source of truth.

**Comment by gforceg** [comment]
@beefsack 
I deleted my fork. Sorry for the delay on this. When you have a moment would you mind transferring ownership?

**Comment by beefsack** [comment]
@gforceg transfer requested, good luck!

**Pull request merged**
